import React from 'react';
import { Grid, Typography } from '@material-ui/core'
import { useTheme } from '@material-ui/core/styles';
import BlogPostPage from '../BlogPostPage'
import economy from '../images/money.jpg'

export default function Economic(){
  return(
    <div>
      <BlogPostPage title="The Economy Isn’t Just About Supply and Demand – It’s About Confidence, Too" date="June 19, 2020" writers="Elyse Barg. Edited by Chaya Kimbell and Tanae Rao" artists="Alice Schroeder" img={economy} link='/blog/economy'/>
          <div style={{display: 'flex', justifyContent: 'center', margin: '20vw',marginTop: '0'}}>

          <Typography variant="p" style={{fontSize: '1.5vw'}}>
          The coronavirus is, first and foremost, a healthcare issue. However, as the pandemic continues to wreak havoc across the world, politicians are beginning to turn their attention towards its economic ramifications. Coronavirus lockdowns have been preventing firms from conducting business as usual, effectively cutting off millions of people from sorely needed income. Hence, some politicians contend, it is necessary to “reopen” the economy as soon as possible so that it may be saved. As this process begins, a myriad of problems are beginning to reveal themselves ― reopening won’t jumpstart the economy if people feel too unsafe to go out and spend, staying shut without running costs is more viable for some businesses than reopening at a loss, and there is also the terrifying prospect of a much larger second wave of infections.
          <br /><br />
          However, in the midst of all of this, I would argue that the most significant economic threat has actually been brewing for years and is now being largely ignored. The Institute of International Finance estimated that worldwide debt surged to $253 trillion US dollars in September 2019 ― more than three times annual economic output. As governments spend billions of dollars in coronavirus response, this rapidly expanding debt bubble seems increasingly likely to burst, taking the rest of the global financial system down with it. Maybe part of why this debt bubble has not been widely discussed is that there is currently no clear solution- with a global pandemic raging, government austerity is undoubtedly not an option, and ballooning debt is clearly the least of many great evils. So with our policy options so severely restricted, what are we to do if the debt crisis comes to fruition? While it may seem like an impossible situation, there are certainly measures that governments can take to stave off a total economic collapse- just probably not in the way that you might think.
          <br /><br />
          Previous financial crises show us that saving the economy perhaps has more to do with psychology than economics. When the global financial crisis first hit in 2007, the US Federal Reserve responded in the usual fashion by cutting interest rates to record lows. Theoretically, this would make it cheaper for people to borrow money, thereby encouraging spending and investment. However, as the crisis worsened in 2008, it was clear that such measures had been gravely insufficient. As such, the US Federal Reserve pioneered an unorthodox programme called ‘Quantitative Easing’ which essentially entailed printing vast quantities of money. To anybody with training in the field of economics ― or familiar with the economic woes of Germany in the wake of World War I ― this sounds like a fundamentally flawed and potentially catastrophic idea. Printing money would increase the supply for money without a corresponding increase in demand, therefore causing the currency to decrease in value and creating substantial amounts of inflation. However, despite the laws of economics, quantitative easing helped to nurse the struggling American economy back to health and was later adopted by central banks around the world to bring about a global recovery from the global financial crisis. The Chairman of the US Federal Reserve at the time, Ben Bernanke, recognised how his seemingly illogical policy brought about strangely positive results. As he put it himself: “The problem with quantitative easing is that it works in practice, but it doesn’t work in theory.” So why did quantitative easing work? And how can that help us in facing the economic challenges that lie ahead?
          <br /><br />
          I would argue that quantitative easing worked because it brought confidence back into the market. At a time of fear and uncertainty, Ben Bernanke made it look like there was a concrete plan to fix the economy, gave it a name, and went through the motions of making it happen in front of a global audience. It didn’t matter that quantitative easing was economically unviable because it was ultimately a performance meant to encourage people and firms to start spending and reinvesting. After all, trust and confidence form the backbone of our economy. As such, when one says that “money makes the world go round”, they are not merely commenting on the power of finance―they are also acknowledging the ubiquity and importance of confidence in a shared narrative.
          <br /><br />
          Nobody can guess what the quantitative easing of the next financial crisis will be, but we can assume that governments and central banks will do everything within their power to try and restore confidence in the shared narrative that is the economy. The world is a very different place to what it was back in 2008, and the quickly devolving trust that has wreaked havoc in the realm of politics may well threaten to derail the prospect of economic recovery. Whether or not that happens remains to be seen, but it will ultimately be our confidence ― both in the financial system and in each other ― that will be the determining factor.
          </Typography>
        </div>
      </div>
  );
}
